baseURL = "https://ruonakoski.fi/"

DefaultContentLanguage = "fi"
languageCode = "fi-fi"
title = "Antti Ruonakoski"
theme = "hyde"

disqusShortname = "ruonakoski"

[languages]
  [languages.fi]
	contentDir = "content/finnish"
    title = "Antti Ruonakoski"
    description = "lintumies full stack-ohjelmoija GIS-nörtti"
    weight = 0
  [languages.en]
  	contentDir = "content/english"
    title = "Antti Ruonakoski"
    description = "birder full stack hobbyist geo nerd OSM contributor"
    weight = 1

[params]
 themeColor = "theme-base-0b"

